FROM node:24-alpine3.23 AS builder-frontend

RUN apk add --no-cache git make

RUN npm install -g pnpm

WORKDIR /src

# Copy source and build
COPY . .

RUN cd web/frontend && pnpm install && pnpm build:backend

FROM golang:1.25-alpine AS builder-backend

RUN apk add --no-cache git make

WORKDIR /src

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source and build
COPY . .

COPY --from=builder-frontend /src/web/backend/dist /src/web/backend/dist

RUN make build-launcher

RUN make build


FROM node:24-alpine3.23

# Install runtime dependencies
RUN apk add --no-cache \
  ca-certificates \
  curl \
  git \
  python3 \
  py3-pip

# Install uv and symlink to system path
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
  ln -s /root/.local/bin/uv /usr/local/bin/uv && \
  ln -s /root/.local/bin/uvx /usr/local/bin/uvx && \
  uv --version

# Copy binary
COPY --from=builder-backend /src/build/picoclaw /usr/local/bin/picoclaw
COPY --from=builder-backend /src/build/picoclaw-launcher /usr/local/bin/picoclaw-launcher

# Create picoclaw home directory
RUN /usr/local/bin/picoclaw onboard

ENTRYPOINT ["picoclaw-launcher"]
CMD ["-public", "-no-browser"]
